### ISSUE TITLE
Comptibility issue with Extension(q-google-map)

### ISSUE THREAD

**Issue by prodigy4801** [mayur091193/q-google-map#12]
Extension(q-google-map): is not compatible with @quasar/app v3.3.3. Required version: ^1.1.0 || ^2.5.5

**Comment by mayur091193** [comment]
Hello,

Use new version 1.0.0 which is compatible with Quasar v2 and @quasar/app v3.

https://www.npmjs.com/package/quasar-app-extension-q-google-map

Thanks
