### ISSUE TITLE
q-google-map extension is not supporting with Quasar v2

### ISSUE THREAD

**Issue by ominfowave** [mayur091193/q-google-map#13]
Hello, q-google-map extension is not supporting with Quasar v2. 
Error: Extension(q-google-map): is not compatible with quasar v2.5.5. Required version: ^1.1.1

**Comment by mayur091193** [comment]
Hello,

Use new version 1.0.0 which is compatible with Quasar v2.

https://www.npmjs.com/package/quasar-app-extension-q-google-map

Thanks
