### ISSUE TITLE
Support for Quasar 2

### ISSUE THREAD

**Issue by haizad** [mayur091193/q-google-map#7]
Hi, first of all thanks for making this wonderful extension. Any plan to make it compatible with Quasar 2.02^?

I got this error when I am trying to compile it.
Extension(q-google-map): is not compatible with quasar v2.0.2. Required version: ^1.1.1

**Comment by h2jose** [comment]
same here, (any plan?)

**Comment by ribrewguy** [comment]
any update on this?

**Comment by ominfowave** [comment]
Same issue with me, any update please?

**Comment by mayur091193** [comment]
Hello,

Use new version 1.0.0 which is compatible with Quasar v2.

https://www.npmjs.com/package/quasar-app-extension-q-google-map

Thanks
