### ISSUE TITLE
q-google-map-marker in not working 

### ISSUE THREAD

**Issue by jmriyaz84** [mayur091193/q-google-map#8]
Hi,
I want to plot a route in google map with various lat & long for that I thought to use your api , but I am getting compilation error on following code , it is asking to provide key for for loop so if i give :key="m.id" , it is not working.
 `<q-google-map-marker
                  :key="m.id"
                  v-for="m in markers"
                  :position="m.position"
                  :clickable="true"
                  :draggable="false"
                >
                </q-google-map-marker>`

If I am not providing key I am getting following error message **"Custom elements in iteration require 'v-bind:key' directives.eslintvue/valid"**

but your basic map is working , please help me to fix this issue

**Comment by mayur091193** [comment]
Please try using the new version 1.0.0. 

https://www.npmjs.com/package/quasar-app-extension-q-google-map

Closing for now due to inactivity, you can re-activate this if you get the same error in the new version.

Thanks for using it!
